#!/usr/bin/env python3

import os
import glob
import pandas as pd
from pathlib import Path

DOCKING_RESULTS_FOLDER = "docking_results"
PROTEIN_FOLDER = "Protein"
COMPLEXES_OUTPUT_FOLDER = "protein_ligand_complexes"
OUTPUT_FORMAT = 'pdb'

def extract_best_pose_from_pdbqt(ligand_output_file):
    lines = []
    inside_model = False
    model_count = 0
    with open(ligand_output_file, 'r') as f:
        for line in f:
            if line.startswith('MODEL'):
                model_count += 1
                if model_count == 1:
                    inside_model = True
                continue
            if line.startswith('ENDMDL'):
                if model_count == 1:
                    break
                continue
            if inside_model:
                lines.append(line)
    return lines

def convert_pdbqt_to_pdb_line(line):
    if line.startswith(('ATOM', 'HETATM')):
        core_data = line[:66]
        try:
            parts = line.strip().split()
            if len(parts) > 0:
                atom_type = parts[-1]
                element = atom_type[:2].strip()
                pdb_line = f"{core_data:<76}{element:>2}\n"
            else:
                pdb_line = core_data.rstrip() + '\n'
        except:
            pdb_line = core_data.rstrip() + '\n'
        return pdb_line
    else:
        return line

def process_protein_lines(protein_lines, output_format='pdb'):
    processed_lines = []
    for line in protein_lines:
        if line.startswith(('ROOT', 'ENDROOT', 'BRANCH', 'ENDBRANCH',
                           'TORSDOF', 'MODEL', 'ENDMDL')):
            continue
        if line.startswith(('ATOM', 'HETATM')):
            if output_format == 'pdb':
                processed_lines.append(convert_pdbqt_to_pdb_line(line))
            else:
                processed_lines.append(line)
        elif line.startswith(('CONECT', 'HEADER', 'TITLE', 'COMPND',
                             'SOURCE', 'REMARK', 'SEQRES', 'HET',
                             'HELIX', 'SHEET', 'SSBOND')):
            processed_lines.append(line)
    return processed_lines

def process_ligand_lines(ligand_lines, output_format='pdb'):
    processed_lines = []
    for line in ligand_lines:
        if line.startswith(('ROOT', 'ENDROOT', 'BRANCH', 'ENDBRANCH', 'TORSDOF')):
            continue
        if line.startswith(('ATOM', 'HETATM')):
            if output_format == 'pdb':
                processed_lines.append(convert_pdbqt_to_pdb_line(line))
            else:
                processed_lines.append(line)
        elif line.startswith('CONECT'):
            processed_lines.append(line)
    return processed_lines

def read_protein_file(protein_file):
    with open(protein_file, 'r') as f:
        lines = f.readlines()
    return lines

def combine_protein_ligand(protein_lines, ligand_lines, protein_name, ligand_name, affinity, output_format='pdb'):
    combined_lines = []
    combined_lines.append("REMARK Protein-Ligand Complex\n")
    combined_lines.append(f"REMARK Protein: {protein_name}\n")
    combined_lines.append(f"REMARK Ligand: {ligand_name}\n")
    combined_lines.append(f"REMARK Binding Affinity: {affinity:.2f} kcal/mol\n")
    combined_lines.append("REMARK Generated by automated docking pipeline\n")
    combined_lines.append("REMARK\n")
    protein_processed = process_protein_lines(protein_lines, output_format)
    combined_lines.extend(protein_processed)
    combined_lines.append("TER\n")
    ligand_processed = process_ligand_lines(ligand_lines, output_format)
    combined_lines.extend(ligand_processed)
    combined_lines.append("END\n")
    return combined_lines

def main():
    print("="*60)
    print("PROTEIN-LIGAND COMPLEX BUILDER (ALL COMBINATIONS)")
    print("="*60)
    os.makedirs(COMPLEXES_OUTPUT_FOLDER, exist_ok=True)
    if not os.path.exists(DOCKING_RESULTS_FOLDER):
        print(f"\nERROR: Docking results folder '{DOCKING_RESULTS_FOLDER}' not found.")
        print("Please run the docking pipeline first.")
        return
    protein_dirs = sorted([d for d in glob.glob(os.path.join(DOCKING_RESULTS_FOLDER, "*"))
                          if os.path.isdir(d)])
    if not protein_dirs:
        print(f"\nERROR: No protein result directories found in {DOCKING_RESULTS_FOLDER}")
        return
    print(f"\nFound {len(protein_dirs)} protein(s) to process")
    print(f"Output format: {OUTPUT_FORMAT.upper()}")
    print(f"Output folder: {COMPLEXES_OUTPUT_FOLDER}\n")
    total_complexes = 0
    successful_combinations = 0
    failed_combinations = 0
    protein_summary = []
    for protein_idx, protein_dir in enumerate(protein_dirs, 1):
        protein_name = os.path.basename(protein_dir)
        print(f"[{protein_idx}/{len(protein_dirs)}] Processing: {protein_name}")
        print("-"*60)
        results_csv = os.path.join(protein_dir, f"{protein_name}_results.csv")
        if not os.path.exists(results_csv):
            print(f" ⚠ WARNING: Results file not found")
            continue
        try:
            df = pd.read_csv(results_csv)
            if df.empty:
                print(f" ⚠ WARNING: No results in CSV file")
                continue
            num_ligands = len(df)
            print(f" Found {num_ligands} ligand(s) to process")
        except Exception as e:
            print(f" ⚠ ERROR reading results CSV: {e}")
            continue
        protein_file_pdbqt = os.path.join(PROTEIN_FOLDER, f"{protein_name}.pdbqt")
        protein_file_pdb = os.path.join(PROTEIN_FOLDER, f"{protein_name}.pdb")
        protein_file = None
        if os.path.exists(protein_file_pdbqt):
            protein_file = protein_file_pdbqt
        elif os.path.exists(protein_file_pdb):
            protein_file = protein_file_pdb
        if not protein_file:
            print(f" ⚠ WARNING: Protein file not found")
            continue
        try:
            protein_lines = read_protein_file(protein_file)
        except Exception as e:
            print(f" ⚠ ERROR reading protein file: {e}")
            continue
        protein_success = 0
        protein_failed = 0
        for idx, row in df.iterrows():
            ligand_name = row['Ligand']
            affinity = row['Best_Affinity_kcal_mol']
            ligand_output = row['Output_File']
            if not os.path.exists(ligand_output):
                print(f" [{idx+1}/{num_ligands}] {ligand_name}: ✗ (Output file not found)")
                protein_failed += 1
                failed_combinations += 1
                continue
            try:
                ligand_lines = extract_best_pose_from_pdbqt(ligand_output)
                if not ligand_lines:
                    print(f" [{idx+1}/{num_ligands}] {ligand_name}: ✗ (Could not extract pose)")
                    protein_failed += 1
                    failed_combinations += 1
                    continue
                combined_lines = combine_protein_ligand(
                    protein_lines,
                    ligand_lines,
                    protein_name,
                    ligand_name,
                    affinity,
                    OUTPUT_FORMAT
                )
                output_filename = f"{protein_name}_{ligand_name}_complex.{OUTPUT_FORMAT}"
                output_path = os.path.join(COMPLEXES_OUTPUT_FOLDER, output_filename)
                with open(output_path, 'w') as f:
                    f.writelines(combined_lines)
                print(f" [{idx+1}/{num_ligands}] {ligand_name}: ✓ (Affinity: {affinity:.2f} kcal/mol)")
                protein_success += 1
                successful_combinations += 1
                total_complexes += 1
            except Exception as e:
                print(f" [{idx+1}/{num_ligands}] {ligand_name}: ✗ (Error: {e})")
                protein_failed += 1
                failed_combinations += 1
                continue
        protein_summary.append({
            'Protein': protein_name,
            'Successful': protein_success,
            'Failed': protein_failed,
            'Total': protein_success + protein_failed
        })
        print(f" Summary: {protein_success} successful, {protein_failed} failed")
        print()
    print("="*60)
    print("FINAL SUMMARY")
    print("="*60)
    print(f"Total proteins processed: {len(protein_dirs)}")
    print(f"Total complexes created: {successful_combinations}")
    print(f"Total failed: {failed_combinations}")
    print(f"Output folder: {COMPLEXES_OUTPUT_FOLDER}")
    print(f"Output format: {OUTPUT_FORMAT.upper()}")
    if protein_summary:
        print("\nPer-Protein Summary:")
        summary_df = pd.DataFrame(protein_summary)
        print(summary_df.to_string(index=False))
        summary_path = os.path.join(COMPLEXES_OUTPUT_FOLDER, "all_complexes_summary.csv")
        summary_df.to_csv(summary_path, index=False)
        print(f"\nSummary saved to: {summary_path}")
    if successful_combinations > 0:
        print(f"\n✓ Generated {successful_combinations} complete complex files")
        print(f" Location: {COMPLEXES_OUTPUT_FOLDER}/")
        print("\nYou can now visualize these in PyMOL, ChimeraX, or other viewers")
    print("\n" + "="*60)
    print("COMPLEX BUILDING COMPLETED")
    print("="*60)

if __name__ == "__main__":
    main()
