#!/usr/bin/env python3

import os
import glob
import pandas as pd
from pathlib import Path
import shutil

DOCKING_RESULTS_FOLDER = "docking_results"
PROTEIN_FOLDER = "Protein"
COMPLEXES_OUTPUT_FOLDER = "protein_ligand_complexes"

OUTPUT_FORMAT = 'pdb'

def extract_best_pose_from_pdbqt(ligand_output_file):
    lines = []
    inside_model = False
    model_count = 0
    with open(ligand_output_file, 'r') as f:
        for line in f:
            if line.startswith('MODEL'):
                model_count += 1
                if model_count == 1:
                    inside_model = True
                continue
            if line.startswith('ENDMDL'):
                if model_count == 1:
                    break
                continue
            if inside_model:
                lines.append(line)
    return lines

def convert_pdbqt_to_pdb(lines):
    pdb_lines = []
    for line in lines:
        if line.startswith(('ATOM', 'HETATM')):
            pdb_line = line[:66].rstrip() + '\n'
            pdb_lines.append(pdb_line)
        elif not line.startswith(('ROOT', 'ENDROOT', 'BRANCH', 'ENDBRANCH', 'TORSDOF')):
            pdb_lines.append(line)
    return pdb_lines

def read_protein_file(protein_file):
    with open(protein_file, 'r') as f:
        lines = f.readlines()
    return lines

def combine_protein_ligand(protein_lines, ligand_lines, output_format='pdb'):
    combined_lines = []
    
    combined_lines.append("REMARK Protein-Ligand Complex\n")
    combined_lines.append("REMARK Generated by automated docking pipeline\n")
    
    if output_format == 'pdb':
        for line in protein_lines:
            if line.startswith(('ATOM', 'HETATM')):
                pdb_line = line[:66].rstrip() + '\n'
                combined_lines.append(pdb_line)
            elif not line.startswith(('ROOT', 'ENDROOT', 'BRANCH', 'ENDBRANCH', 'TORSDOF', 'MODEL', 'ENDMDL')):
                combined_lines.append(line)
    else:
        combined_lines.extend(protein_lines)
    
    combined_lines.append("TER\n")
    
    if output_format == 'pdb':
        ligand_pdb_lines = convert_pdbqt_to_pdb(ligand_lines)
        combined_lines.extend(ligand_pdb_lines)
    else:
        combined_lines.extend(ligand_lines)
    
    combined_lines.append("END\n")
    
    return combined_lines

def main():
    print("="*60)
    print("PROTEIN-LIGAND COMPLEX BUILDER")
    print("="*60)
    
    os.makedirs(COMPLEXES_OUTPUT_FOLDER, exist_ok=True)
    
    if not os.path.exists(DOCKING_RESULTS_FOLDER):
        print(f"\nERROR: Docking results folder '{DOCKING_RESULTS_FOLDER}' not found.")
        print("Please run the docking pipeline first.")
        return
    
    protein_dirs = [d for d in glob.glob(os.path.join(DOCKING_RESULTS_FOLDER, "*"))
                    if os.path.isdir(d)]
    
    if not protein_dirs:
        print(f"\nERROR: No protein result directories found in {DOCKING_RESULTS_FOLDER}")
        return
    
    print(f"\nFound {len(protein_dirs)} protein(s) to process\n")
    
    successful_combinations = 0
    
    for protein_dir in protein_dirs:
        protein_name = os.path.basename(protein_dir)
        print(f"Processing: {protein_name}")
        
        results_csv = os.path.join(protein_dir, f"{protein_name}_results.csv")
        
        if not os.path.exists(results_csv):
            print(f" ⚠ WARNING: Results file not found: {results_csv}")
            continue
        
        try:
            df = pd.read_csv(results_csv)
            if df.empty:
                print(f" ⚠ WARNING: No results in CSV file")
                continue
            
            best_result = df.iloc[0]
            best_ligand_name = best_result['Ligand']
            best_affinity = best_result['Best_Affinity_kcal_mol']
            best_ligand_output = best_result['Output_File']
            
            print(f" Best ligand: {best_ligand_name}")
            print(f" Best affinity: {best_affinity:.2f} kcal/mol")
        except Exception as e:
            print(f" ⚠ ERROR reading results CSV: {e}")
            continue
        
        protein_file_pdbqt = os.path.join(PROTEIN_FOLDER, f"{protein_name}.pdbqt")
        protein_file_pdb = os.path.join(PROTEIN_FOLDER, f"{protein_name}.pdb")
        protein_file = None
        
        if os.path.exists(protein_file_pdbqt):
            protein_file = protein_file_pdbqt
        elif os.path.exists(protein_file_pdb):
            protein_file = protein_file_pdb
        
        if not protein_file:
            print(f" ⚠ WARNING: Protein file not found")
            continue
        
        if not os.path.exists(best_ligand_output):
            print(f" ⚠ WARNING: Ligand output file not found: {best_ligand_output}")
            continue
        
        try:
            protein_lines = read_protein_file(protein_file)
            
            ligand_lines = extract_best_pose_from_pdbqt(best_ligand_output)
            
            if not ligand_lines:
                print(f" ⚠ WARNING: Could not extract ligand pose")
                continue
            
            combined_lines = combine_protein_ligand(protein_lines, ligand_lines, OUTPUT_FORMAT)
            
            output_filename = f"{protein_name}_{best_ligand_name}_complex.{OUTPUT_FORMAT}"
            output_path = os.path.join(COMPLEXES_OUTPUT_FOLDER, output_filename)
            
            with open(output_path, 'w') as f:
                f.writelines(combined_lines)
            
            print(f" ✓ Complex saved: {output_filename}")
            successful_combinations += 1
        except Exception as e:
            print(f" ⚠ ERROR creating complex: {e}")
            continue
        
        print()
    
    print("="*60)
    print("SUMMARY")
    print("="*60)
    print(f"Successfully created {successful_combinations}/{len(protein_dirs)} complexes")
    print(f"Output folder: {COMPLEXES_OUTPUT_FOLDER}")
    print(f"Output format: {OUTPUT_FORMAT.upper()}")
    
    if successful_combinations > 0:
        print("\nGenerated complex files:")
        complex_files = sorted(glob.glob(os.path.join(COMPLEXES_OUTPUT_FOLDER, f"*.{OUTPUT_FORMAT}")))
        for cf in complex_files:
            print(f" - {os.path.basename(cf)}")
    
    print("\n" + "="*60)
    print("COMPLEX BUILDING COMPLETED")
    print("="*60)

if __name__ == "__main__":
    main()

